import sys
import pathlib
import csv
import logging
from logging.handlers import RotatingFileHandler
import os, stat
import time
logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)
formatter = logging.Formatter("%(asctime)s; %(name)s; %(levelname)s; "
                "%(message)s; %(lineno)d; %(funcName)s", datefmt="%Y-%m-%d %H:%M:%S")

console_handler = logging.StreamHandler()
console_handler.setFormatter(formatter)
logger.addHandler(console_handler)


file_handler = RotatingFileHandler(f"{__name__}.log", maxBytes=1000000, backupCount=3)
file_handler.setFormatter(formatter)
logger.addHandler(file_handler)



BASE_DIR = pathlib.Path(__file__).resolve().parent
DATA_FILE = BASE_DIR / "user_data.csv"
INDEX_FILE = BASE_DIR / "counter.txt"
UPDATED_FILE = BASE_DIR / "update.csv"
print(os.access(".", os.W_OK))
def index_counter(index):
    with open(INDEX_FILE, mode='w', encoding='utf-8') as f:
        f.write(str(index))


def next_index():
    try:
        with open(INDEX_FILE, mode='r', encoding='utf-8') as f:
            index = f.read().strip()
            return int(index) if index else 0
    except (FileNotFoundError, ValueError):
        return 0
    

# add tasks
def add_tsk():
    print("Use comma, To seperate tasks.")
    while True:
        input_tasks = input("Enter Task/s: ").strip().split(',')
        if input_tasks == "":
            print("You didn't enter a single task, try again!")
            continue
        break
    with open(DATA_FILE, mode='a+', encoding='utf-8', newline='') as f:
        writer = csv.writer(f)
        added_task = []
        for i, task in enumerate (input_tasks, start=next_index()):
            if task.isspace():
                continue
            writer.writerow([i,task])
            added_task.append([i,task])
        print('\nThe task/s have been saved with following IDs;')
        print('ID   Task')
        for task in added_task:
            print(f"{task[0]} - {task[1].capitalize()}")
        index = i + 1
        index_counter(index)
        cmd()

def update():
    inst = "\nInstructions:\n1.Press 'q' for main menu, 0 for exiting app.\n" \
    "2.Please note that, by updating a task, we mean you can change Its name, however you cannot change a task Id.\n" \
    "3.A task Id is a unique number, generated by system automatically, at the time of creating a task.\n" \
    "4.For updating a task name, you have to provide Its Id, which, in case you don't know, can find in main menu, " \
    "where all the saved tasks is enlisted with their individual Ids."
    print(inst)
    while True:
        #taking task ID
        tk_id = (input('Enter Task Id: ' ).strip())
        
        if tk_id.lower() == 'q':
            main_menu()
            break
        if tk_id == '':
            print("ID can't be empty, please provide a valid Id to process further!")
            continue
        try:
            tk_id = int(tk_id)
            if tk_id == 0:
                sys.exit()            
            break
        except ValueError:
            print('Task Id is a numeric value!')
            continue 


    with open(DATA_FILE, mode='r', encoding='utf-8', newline='') as infile:
        reader = csv.reader(infile)
        rows = list(reader)
        updated_row = []

        found = False
        for i in rows:
            if not i:
                continue
            if int(i[0]) == tk_id:
                found = True
                print(f'''The Task with ID{tk_id} is "{i[1].title()}". Are you sure you want to change Its name?''')

                while True:
                    cofirm = input("Enter 'y' for yes, 'n' to cancel request, " \
                    "on which you'll redirected to main manu: ")
                    if cofirm.lower() == 'y':
                        new_tk = input("Enter New Task Name: ")
                        i[1] = new_tk
                        break
                    elif cofirm.lower() == 'n':
                        main_menu()
                        break
                    else:
                        print("Please provide a valid Input! try again.")
                    continue
        if not found:            
            print(f"There is no task with ID-{tk_id}!\nPlease check saved task in main menu.")
            cmd()
            
        with open(UPDATED_FILE, mode='w', encoding='utf-8', newline='') as outfile:
            writer = csv.writer(outfile)
            for row in rows:
                writer.writerow(row)
            if row[0] == tk_id:
    
                print(f"The Task: {updated_row[1]} with ID{[row[0]]} has been upadated!")
    
    for _ in range(5):
        try:
            os.replace(UPDATED_FILE, DATA_FILE)
            print("Task has been upadated successfully!") 
            break          
        except PermissionError:
            time.sleep(0.2)

# deleted task
def delete():
    inst = "\nType the number corresponding to your choice:\n1.Delete file 2.Deleted file data 3.Deleted a task/s."
    print(inst)
    
    while True:
        try:
            u_input = input("Enter: ")
            if u_input.strip() == "":
                print("Input can't be empty! Please try again.")
                continue
            if int(u_input) < 0 or int(u_input) > 3:
                print("You can only put value between 1 and 3!")
                continue
            break
        except TypeError:
            print("Only numeric value(e.g 1, 2,3) are allowed! try again.")
            continue
        

    with open(DATA_FILE, mode='w') as f:
        pass


def view_tk():
    try:
        with open(DATA_FILE, mode='r', encoding='utf-8', newline='') as f:
            reader = csv.reader(f)
            for row in reader:
                if not reader:
                    print('No task, press 1 to add a task.')
                    cmd()
                    break
                print(f"{int(row[0])} - {row[1].title()}")
            cmd()
    except FileNotFoundError as e:
        logger.exception("User Couldn't able to view the saved tasks.", e)
        print(f"There seems to be some issue fetching the task!\nSorry for the Inconvenience."\
              "We'll fix the problem as soon as possible.")
        


#taking user command
def cmd():
    #instruction
    print("\nEnter 'q' in any command for Main-Menu.")
    print(f"Commands: 0.Exit 1.Add 2.Update 3.View 4.Delete")   
    while True:
        try:
            user_command = input("Enter Your Command: ").strip()
            if user_command == "":
                print("Input can't be empty, please try again!")
                continue
            if user_command.lower() == 'q':
                main_menu()
                break
            if int(user_command) < 0 or int(user_command) > 4:
                print ("You can only put value between 1 and 4!")
                continue
            break
        except ValueError:
            print("Please, Enter only numeric value!")
            continue
            #matching user command
    match int(user_command):
        case 0:
            while True:
                exit =input("Are you sure you want to close the application? yes(y)/no(n): ").lower()
                if exit == 'y':
                    print('Thankyou for using the tool.')
                    sys.exit()
                    break
                elif exit == 'n':
                    break
                else:
                    print("Invalid Input! try again.")
                    continue
        case 1:
            add_tsk()
        case 2:
            update()
        case 3:
            view_tk()
        case 4:
            delete()
            
        
        


def main_menu():
    print("\n✅ Task Manager") #app title
    inst = (f"\nCommands are as follows:\n0.Exit 1.Add 2.Update 3.View 4.Delete\nInfo: Only numeric input is allowed.\n")
    print(inst)
    
    try:
        with open(DATA_FILE, encoding='utf-8', newline='', mode='r') as f:
            if f.read().strip() == '':
                print('No task, press 1 to add new task!')
                cmd()
            else:
                fieldnames = ['Id', 'Task']
                reader = csv.DictReader(f, fieldnames=fieldnames)       
                print('All Tasks\nID Task')
                f.seek(0)
                for row in reader:
                    if row['Task'] == '':
                        continue 
                    print(f"{int(row['Id'])} - {row['Task'].title()}")
                cmd()
    except FileNotFoundError as e:
        logger.exception(e)
        print(f"No saved task found! \n Press 1 to add new task/s.")
    cmd()

main_menu()
      
     




# if "__name__" == "__main__":
